export interface Statistics {
  totalUsers: number
  totalVerifiedUsers: number
  totalPets: number
  totalPosts: number
  totalProducts: number
  totalAdoptionRequests: number
  totalComments: number
  totalReports: number
  totalCrowdfunding: number
  totalCrowdfundingAmount: number
  totalSponsors: number
  totalBanners: number
  totalMessages: number
  totalUnreadMessages: number
  totalNotifications: number
  totalMediaFiles: number
  totalFavorites: number
  totalShares: number
  totalLikes: number
  usersCreatedToday: number
  postsCreatedToday: number
  productsCreatedToday: number
  adoptionRequestsToday: number
  usersCreatedThisWeek: number
  postsCreatedThisWeek: number
  productsCreatedThisWeek: number
  adoptionRequestsThisWeek: number
  usersCreatedThisMonth: number
  postsCreatedThisMonth: number
  productsCreatedThisMonth: number
  adoptionRequestsThisMonth: number
  usersGrowthPercentage: number
  postsGrowthPercentage: number
  productsGrowthPercentage: number
  adoptionRequestsGrowthPercentage: number
  commentsGrowthPercentage: number
  reportsGrowthPercentage: number
  crowdfundingGrowthPercentage: number
  nonBannedPets: number
  nonBannedPosts: number
  nonBannedProducts: number
  nonBannedComments: number
  activeBannersEnabled: number
}
